export const tongueCatagories = [
  "jiankangshe",
  "botaishe",
  "hongshe",
  "zishe",
  "pangdashe",
  "shoushe",
  "hongdianshe",
  "liewenshe",
  "chihenshe",
  "baitaishe",
  "huangtaishe",
  "heitaishe",
  "huataishe",
  "shenquao",
  "shenqutu",
  "gandanao",
  "gandantu",
  "piweiao",
  "piweitu",
  "xinfeiao",
  "xinfeitu",
];

export const tongueCatagoriesMap = {
  jiankangshe: "健康舌",
  botaishe: "剝苔舌",
  hongshe: "紅舌",
  zishe: "紫舌",
  pangdashe: "胖大舌",
  shoushe: "瘦舌",
  hongdianshe: "紅點舌",
  liewenshe: "裂紋舌",
  chihenshe: "齒痕舌",
  baitaishe: "白苔舌",
  huangtaishe: "黃苔舌",
  heitaishe: "黑苔舌",
  huataishe: "滑苔舌",
  shenquao: "腎區凹",
  shenqutu: "腎區凸",
  gandanao: "肝膽凹",
  gandantu: "肝膽凸",
  piweiao: "脾胃凹",
  piweitu: "脾胃凸",
  xinfeiao: "心肺凹",
  xinfeitu: "心肺凸",
} satisfies Record<string, string>;
